Repository insightsengineering/dunlin, pull requests merged in 2024-10, with the labels that each got.

#162 Readable code poc@main
  NAMESPACE
  NEWS.md
  R/filter.R
  R/reformat.R
  R/utils.R
  _pkgdown.yaml
  man/get_arg.Rd
  man/h_expand_all_datasets.Rd
  man/log_filter.Rd
  man/reformat.Rd
  tests/testthat/_snaps/filter.md
  tests/testthat/test-filter.R
  tests/testthat/test-reformat.R
  tests/testthat/test-utils.R
Labels: chevron

#164 163 since format is printed, we may want to improve how formats are printed, currently it is
  NEWS.md
  R/rules.R
  tests/testthat/_snaps/rules.md
  tests/testthat/test-rules.R
Labels: chevron

#165 Hierarchical metadata@main
  NAMESPACE
  NEWS.md
  R/rules.R
  _pkgdown.yaml
  man/combine_list_rules.Rd
  man/combine_rules.Rd
  tests/testthat/test-rules.R
Labels: chevron

#167 [skip vbump] release v0.1.8
  DESCRIPTION
  NEWS.md
Labels: chevron, release

#170 rm staged dep
  .github/workflows/check.yaml
  staged_dependencies.yaml
Labels: chevron, sme
